/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.lsy.struts.action;

import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.lsy.struts.common.BaseAction;
import com.lsy.struts.common.BaseForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-22-2007
 * 
 * XDoclet definition:
 * @struts.action path="test" name="commonActionForm" parameter="reqCode" scope="request" validate="true"
 */
public class TestAction extends BaseAction {
	/*
	 * Generated Methods
	 */
	
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward test(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		BaseForm commonActionForm = (BaseForm) form;
		Map sto = commonActionForm.getStoMap();
		return null;
	}
}